version: '3.8'
services:
  api:
    build: ./api
    container_name: api_backend
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - api_modules:/app/node_modules
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - client_modules:/app/node_modules
    stdin_open: true
    tty: true
  mongo:
    image: mongo:4.2.8
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '9999:27017'
    volumes:
      - ./mongodb:/data/db
    restart: always
volumes:
  api_modules: {}
  client_modules: {}